package org.ttk.maxwell.dao;

import java.io.Serializable;
import java.util.Date;

public class MaxwellTest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maxwell_test.id
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maxwell_test.maxwell_username
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    private String maxwellUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maxwell_test.maxwell_password
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    private String maxwellPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maxwell_test.create_time
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column maxwell_test.update_time
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maxwell_test.id
     *
     * @return the value of maxwell_test.id
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maxwell_test.id
     *
     * @param id the value for maxwell_test.id
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maxwell_test.maxwell_username
     *
     * @return the value of maxwell_test.maxwell_username
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public String getMaxwellUsername() {
        return maxwellUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maxwell_test.maxwell_username
     *
     * @param maxwellUsername the value for maxwell_test.maxwell_username
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public void setMaxwellUsername(String maxwellUsername) {
        this.maxwellUsername = maxwellUsername == null ? null : maxwellUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maxwell_test.maxwell_password
     *
     * @return the value of maxwell_test.maxwell_password
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public String getMaxwellPassword() {
        return maxwellPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maxwell_test.maxwell_password
     *
     * @param maxwellPassword the value for maxwell_test.maxwell_password
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public void setMaxwellPassword(String maxwellPassword) {
        this.maxwellPassword = maxwellPassword == null ? null : maxwellPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maxwell_test.create_time
     *
     * @return the value of maxwell_test.create_time
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maxwell_test.create_time
     *
     * @param createTime the value for maxwell_test.create_time
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column maxwell_test.update_time
     *
     * @return the value of maxwell_test.update_time
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column maxwell_test.update_time
     *
     * @param updateTime the value for maxwell_test.update_time
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", maxwellUsername=").append(maxwellUsername);
        sb.append(", maxwellPassword=").append(maxwellPassword);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}