package org.ttk.maxwell.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.ttk.maxwell.dao.MaxwellTest;
import org.ttk.maxwell.dao.MaxwellTestExample;

public interface MaxwellTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int countByExample(MaxwellTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int deleteByExample(MaxwellTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int insert(MaxwellTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int insertSelective(MaxwellTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    List<MaxwellTest> selectByExample(MaxwellTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    MaxwellTest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int updateByExampleSelective(@Param("record") MaxwellTest record, @Param("example") MaxwellTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int updateByExample(@Param("record") MaxwellTest record, @Param("example") MaxwellTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int updateByPrimaryKeySelective(MaxwellTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table maxwell_test
     *
     * @mbggenerated Sun Jun 12 01:16:09 CST 2022
     */
    int updateByPrimaryKey(MaxwellTest record);
}